CREATE DATABASE virtualdc; /* Danilo Alves dos Santos */
USE virtualdc;

CREATE TABLE cadfun(
CODFUN INT NOT NULL PRIMARY KEY,
NOME VARCHAR(40),
DEPTO VARCHAR(2),
FUNCAO VARCHAR(20),
SALARIO DECIMAL(10,2)
);

-- POPULANDO
INSERT INTO cadfun (CODFUN,NOME, DEPTO, FUNCAO, SALARIO) VALUES (12, 'CARLOS ALBERTO','03','VENDEDOR',1530.00);
INSERT INTO cadfun VALUES (2,'WILSON DE MACEDO', '03', 'PROGRAMADOR',1050.00);
INSERT INTO cadfun VALUES (15,'MARCELO HENRIQUE', '02', 'GERENTE', 1985.75);
INSERT INTO cadfun VALUES (7, 'APARECIDA SILVA', '03', 'SECRETARIA',1200.50);
INSERT INTO cadfun VALUES (9,'SOLANGE PACHECO', '05', 'SUPERVISORA',1599.51);
INSERT INTO cadfun VALUES (6,'MARCELO SOUZA', '03', 'ANALISTA', 2250.11);
INSERT INTO cadfun VALUES (1, 'CELIA NASCIMENTO', '02', 'SECRETARIA', 1200.50);
INSERT INTO cadfun VALUES (5,'AUGUSTO SOUZA','03','PROGRAMADOR',1050.00);
INSERT INTO cadfun VALUES (4,'CARLOS BASTOS','05','VENDEDOR',1530.00);
INSERT INTO cadfun VALUES (25,'PEDRO SILVA','03','SUPERVISOR',1599.51);
INSERT INTO cadfun VALUES (3,'ANA BASTOS','05','VENDEDORA',1530.00);
INSERT INTO cadfun VALUES (10,'PAULO DA SILVA','02','VENDEDOR',1530.00);

-- MOSTRANDO VALORES
SELECT * FROM cadfun;
SELECT NOME FROM cadfun;
SELECT NOME,FUNCAO FROM cadfun;
SELECT NOME FROM cadfun WHERE DEPTO = '03';
SELECT NOME,SALARIO FROM cadfun ORDER BY NOME;
SELECT NOME,SALARIO FROM cadfun ORDER BY NOME DESC;
SELECT NOME,DEPTO FROM cadfun ORDER BY DEPTO,NOME DESC; /* ELE MOSTRA O DEPARTAMENTO POR ORDEM CRESCENTE E NOME POR NOME DECRESENTE */
SELECT NOME FROM cadfun WHERE DEPTO ='03' ORDER BY NOME;

-- ATUALIZANDO O SALARIO DO FUNCIONARIO
SELECT * FROM cadfun WHERE CODFUN = 7;
UPDATE cadfun SET SALARIO = 2300.56 WHERE CODFUN = 7;
SELECT * FROM cadfun WHERE CODFUN = 7;

-- ATUALIZANDO DEPARTAMENTO DO FUNCIONARIO
SELECT * FROM cadfun WHERE NOME = 'ANA BASTO';
UPDATE cadfun SET DEPTO = '03' WHERE NOME = 'ANA BASTO';
SELECT NOME FROM cadfun WHERE NOME = 'ANA BASTO';

-- 10% DE AUMENTO PARA TODOS OS FUNCIONARIOS
SELECT * FROM cadfun;
UPDATE cadfun SET SALARIO = SALARIO * 1.10; /*TODOS FUNCIONARIOS RECEBEM 10% DE AUMENTO*/
SELECT * FROM cadfun;

-- DELETANDO FUNCIONARIO
SELECT * FROM cadfun;
DELETE FROM cadfun WHERE NOME = 'MARCELO SOUZA';
SELECT * FROM cadfun;

-- ADICIONANDO ATRIBUTO DATA DE DEMISSÃO NA TABELA *cadfun*
SELECT * FROM cadfun;
ALTER TABLE cadfun ADD ADMISSAO DATE;
SELECT * FROM cadfun;

-- ATUALIZANDO DATA DE DEMISSÃO DOS EX-FUNCIONARIOS
UPDATE cadfun SET ADMISSAO = '2006-01-15' WHERE CODFUN = 2;
UPDATE cadfun SET ADMISSAO = '1999-10-21' WHERE CODFUN = 3;
UPDATE cadfun SET ADMISSAO = '2004-10-21' WHERE CODFUN = 4;
UPDATE cadfun SET ADMISSAO = '2006-04-26' WHERE CODFUN = 5;
UPDATE cadfun SET ADMISSAO = '1980-05-10' WHERE CODFUN = 7;
UPDATE cadfun SET ADMISSAO = '1999-12-15' WHERE CODFUN = 9;
UPDATE cadfun SET ADMISSAO = '2000-12-21' WHERE CODFUN = 12;
UPDATE cadfun SET ADMISSAO = '2000-12-21' WHERE CODFUN = 25;
SELECT * FROM cadfun;

UPDATE cadfun SET ADMISSAO = '2006-05-25' WHERE CODFUN = 15;
INSERT INTO cadfun VALUES (20,'AUDREY TOLEDO','02','SUPERVISORA','1700.00','2006-05-07');
INSERT INTO cadfun VALUES (22,'MARCOS HENRIQUE','02','GERENTE','2184.33','2006-01-07');
INSERT INTO cadfun VALUES (24,'MARCOS HENRIQUE','02','GERENTE','2184.33','2006-10-07');
SELECT * FROM cadfun;

-- MOSTRANDO TUDO ONDE O MÊS DE DEMISSÃO FOR 12 ( DEZEMBRO )
SELECT * FROM cadfun WHERE MONTH(ADMISSAO) = 12;

-- CRIANDO NOVA TABELA
CREATE TABLE ARQUIVOMORTO (
CODFUN INT NOT NULL,
NOME VARCHAR(40),
DEPTO CHAR(2),
FUNCAO VARCHAR(20),
SALARIO DECIMAL(10,2),
ADMISSAO DATE
);

-- INSERINDO DADOS DA TABELA cadfun ONDE CODFUN = 12,NA TABELA ARQUIVOMORTO, 
INSERT INTO ARQUIVOMORTO
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO
FROM cadfun
WHERE CODFUN = 12;

-- APAGANDO REGISTRO
SELECT * FROM cadfun;
DELETE FROM cadfun WHERE CODFUN = 12;
SELECT * FROM cadfun;

-- MOSTRA OS FUNCIONARIOS DA TABELA CADFUN QUE TEM O SALARIO IGUAL AO QUE ESTÁ NA TABELA ARQUIVOMORTO QUE TEM O CODFUN = 12
SELECT * FROM cadfun WHERE SALARIO = (SELECT SALARIO FROM ARQUIVOMORTO WHERE CODFUN = 12);

-- MOSTRA OS FUNCIONARIOS DA TABELA CADFUN QUE TEM O MESMO DEPARTAMENTO DO FUNCIONARIO QUE ESTÁ NA TABELA ARQUIVOMORTO QUE TEM O CODFUN = 12
SELECT * FROM cadfun WHERE DEPTO = (SELECT DEPTO FROM ARQUIVOMORTO WHERE CODFUN = 12);

-- EXERCÍCIOS

/* A */ SELECT NOME, FUNCAO FROM cadfun;
/* B */ SELECT CODFUN, NOME, FUNCAO FROM cadfun;
/* C */ SELECT CODFUN, NOME, FUNCAO, DEPTO FROM cadfun;
/* D */ SELECT NOME FROM cadfun WHERE DEPTO = '05';
/* E */ SELECT NOME, DEPTO FROM cadfun WHERE FUNCAO = 'VENDEDOR';
/* F */ SELECT NOME,SALARIO FROM cadfun WHERE DEPTO = '03';
/* G */ SELECT NOME, FUNCAO FROM cadfun ORDER BY FUNCAO DESC;
/* H */ SELECT NOME, FUNCAO FROM cadfun ORDER BY FUNCAO, NOME DESC; 
/* I */ SELECT * FROM cadfun WHERE MONTH(ADMISSAO) = 10;






